# Generated by Django 5.1.2 on 2024-10-24 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Categoria', models.CharField(max_length=100)),
                ('Descripcion_Categoria', models.CharField(max_length=1000)),
                ('id_Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.receta')),
            ],
        ),
    ]
